name: SmallCloud-CD

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

env:
  CODE_DEPLOY_APPLICATION_NAME: github-action-cd
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: aym
  PROJECT_NAME: Smallcloud

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami
